openapi: 3.0.0
info:
  title: USD to JPY Conversion API
  description: API for converting between US Dollars (USD) and Japanese Yen (JPY) with support for TTS, TTB, and TTM rates.
  version: 1.0.0

servers:
  - url: https://raw.githubusercontent.com/making/usd-to-jpy/main
    description: Main server

paths:
  /{year}/{month}/{day}/{rateType}:
    get:
      summary: Get conversion rate
      description: Retrieve the conversion rate from USD to JPY for a specific date and rate type (TTS, TTB, TTM).
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: string
          description: Year in YYYY format
        - name: month
          in: path
          required: true
          schema:
            type: string
          description: Month in MM format
        - name: day
          in: path
          required: true
          schema:
            type: string
          description: Day in DD format
        - name: rateType
          in: path
          required: true
          schema:
            type: string
            enum: [TTS, TTB, TTM]
          description: Type of the rate (TTS, TTB, TTM)
      responses:
        '200':
          description: Successful response with the conversion rate
          content:
            text/plain:
              schema:
                type: string
                example: "142.45"
        '404':
          description: Not Found

